import Head from 'next/head'
import Link from 'next/link'
import { Store } from '../utils/Store';
import { useContext } from 'react';

function Layout({title, children}) {
    const {state,dispatch} = useContext(Store)
    const {cart} = state
    return ( <>
    <Head>
        <title>{ title ? title  + ' - Amazona' : ' Amazona'}</title>
        <meta name="description" content="Generated by "/>
    </Head>
             <div className='flex  min-h-screen flex-col justify-between '>
            <header>
                <nav className='flex h-12 items-center px-4  justify-between shadow-md'>
                    <Link href="/" className='text-lg'>
                        stockShop
                    </Link>
                    <div> 
                <Link href='/cart' className='p-2'>Cart
                {cart.cartItems.length>0 && (<span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                {cart.cartItems.reduce((a,c)=>{return a+c.quantity},0)}
                </span>)}
                </Link>
                <Link href='/signup' className='p-2'>Login</Link>
             </div>
                </nav>
            
            </header>

            <main className='container m-auto mt-4 px-4'>
            {children}
            </main>

            <footer className='flex h-10 justify-center items-center shadow-inner'>
            <p>Copyright © 2022 Amazona</p>
            </footer>
            </div>
             </> );
}

export default Layout;